First, the most import element Tensor
Tensor is quite the same with ndarray in numpy 



In [5]:
import torch
import numpy as np

In [12]:
t = torch.Tensor(5, 3)
n = np.empty((5, 3))
print(t, t.shape)
print(n, n.shape)

tensor([[-4.8994e+14,  4.5874e-41,  1.1169e+23],
        [ 3.0775e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00,  1.1138e+23],
        [ 3.0775e-41,  0.0000e+00,  1.7163e-05],
        [ 0.0000e+00,  9.4514e-03,  0.0000e+00]]) torch.Size([5, 3])
[[4.66041149e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.94065646e-324]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.41098469e-323]
 [1.74918235e-309 1.25622152e-311 1.02765654e-321]] (5, 3)


In [4]:
torch.rand(5, 3)

tensor([[0.0543, 0.3960, 0.3582],
        [0.7760, 0.5389, 0.1884],
        [0.4290, 0.3583, 0.9707],
        [0.3591, 0.1661, 0.0415],
        [0.2520, 0.2173, 0.7167]])

In [13]:
t2 = torch.rand(5, 3)

In [14]:
t + t2

tensor([[-4.8994e+14,  3.4227e-01,  1.1169e+23],
        [ 1.0919e-02,  3.0073e-01,  1.7690e-01],
        [ 1.5206e-03,  7.1752e-01,  1.1138e+23],
        [ 6.6636e-01,  6.3252e-01,  7.3975e-01],
        [ 5.1726e-01,  8.9382e-02,  6.2015e-02]])

In [15]:
torch.cuda.is_available()

True

In [18]:
from torch.autograd import Variable

x = Variable(torch.ones(2,2), requires_grad=True)

In [20]:
y = x + 2

In [22]:
z = y * y * 3

In [23]:
out = z.mean()

In [25]:
out.backward()

In [26]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [29]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.norm() < 1000:
    y = y * 2
    






In [31]:
gradients = torch.Tensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [2]:
import numpy as np
import math

In [32]:
x.dtype

dtype('float64')

In [27]:
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)
print(x, y)

[-3.14159265 -3.13844949 -3.13530633 ...  3.13530633  3.13844949
  3.14159265] [-1.22464680e-16 -3.14315906e-03 -6.28628707e-03 ...  6.28628707e-03
  3.14315906e-03  1.22464680e-16]


In [93]:
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()
e = np.random.randn()
f = np.random.randn()


In [90]:
learning_rate = 4e-10

In [69]:
for t in range(100000):
    y_pred = a + b*x + d*x**3 + e*x**5 + f*x**7

    loss = np.square(y - y_pred).sum() 
    if t % 5000 == 99:
        print(t, loss)

    grad_y_pred = 2 * (y - y_pred)
    a_grad = grad_y_pred.sum()
    b_grad = (grad_y_pred * x).sum()
    d_grad = (grad_y_pred * x ** 3).sum()
    e_grad = (grad_y_pred * x ** 5).sum()
    f_grad = (grad_y_pred * x ** 7).sum()

    a += a_grad * learning_rate
    b += b_grad * learning_rate
    d += d_grad * learning_rate
    e += e_grad * learning_rate
    f += f_grad * learning_rate


print(f'Result: y = {a} + {b} x + {d} x^3 + {e} x^5 + {f} x^7')





99 763.9751828133012
5099 757.5023886903538
10099 751.0861867598618
15099 744.7260764603152
20099 738.4215617048901
25099 732.1721508410533
30099 725.9773566105089
35099 719.8366961095446
40099 713.7496907496449
45099 707.7158662185958
50099 701.7347524418744
55099 695.8058835443524
60099 689.9287978124073
65099 684.1030376563908
70099 678.3281495733854
75099 672.6036841103125
80099 666.9291958274387
85099 661.3042432621145
90099 655.7283888929356
95099 650.2011991041583
Result: y = -0.4439630541122855 + 1.153627950988562 x + -0.6392832735384499 x^3 + 0.13619872819004 x^5 + -0.008772475599070758 x^7


In [95]:
import torch
import math

dtype = torch.float64
device = torch.device('cpu')

device = torch.device("cuda:0") # Uncomment this to run on GPU




In [96]:
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

In [97]:
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)
e = torch.randn((), device=device, dtype=dtype)
f = torch.randn((), device=device, dtype=dtype)


In [98]:
for t in range(500000):
    y_pred = a + b*x + d*x**3 + e*x**5

    loss = (y - y_pred).pow(2).sum().item()
    if t % 5000 == 99:
        print(t, loss)

    grad_y_pred = 2 * (y - y_pred)
    a_grad = grad_y_pred.sum()
    b_grad = (grad_y_pred * x).sum()
    d_grad = (grad_y_pred * x ** 3).sum()
    e_grad = (grad_y_pred * x ** 5).sum()

    a += a_grad * learning_rate
    b += b_grad * learning_rate
    d += d_grad * learning_rate
    e += e_grad * learning_rate


print(f'Result: y = {a.item()} + {b.item()} x + {d.item()} x^3 + {e.item()} x^5')

99 342222.0314785214
5099 13936.008191303183
10099 12472.592888638937
15099 11174.972430907685
20099 10024.163203668544
25099 9003.35842111805
30099 8097.678461016789
35099 7293.949835035301
40099 6580.5095101570205
45099 5947.03167348092
50099 5384.37436625868
55099 4884.4437082509985
60099 4440.073694868043
65099 4044.919780961708
70099 3693.3646700003073
75099 3380.4349087204328
80099 3101.7270479145627
85099 2853.342272159801
90099 2631.82852713739
95099 2434.129284602057
100099 2257.538183691864
105099 2099.6588745882837
110099 1958.3694678405514
115099 1831.7910611047687
120099 1718.259875637089
125099 1616.3025885187533
130099 1524.6144940771678
135099 1442.0401700076077
140099 1367.5563609180736
145099 1300.25682496991
150099 1239.3389184561772
155099 1184.0917189853253
160099 1133.8855107997865
165099 1088.1624759996776
170099 1046.4284533604673
175099 1008.2456422977064
180099 973.2261435752812
185099 941.0262407877226
190099 911.3413376541074
195099 883.9014759057283
200099 

In [116]:
# -*- coding: utf-8 -*-
import torch
import math

dtype = torch.float
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

# Create Tensors to hold input and outputs.
# By default, requires_grad=False, which indicates that we do not need to
# compute gradients with respect to these Tensors during the backward pass.
x = torch.linspace(-math.pi, math.pi, 2000, dtype=dtype)
y = torch.sin(x)

# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), dtype=dtype, requires_grad=True)
b = torch.randn((), dtype=dtype, requires_grad=True)
c = torch.randn((), dtype=dtype, requires_grad=True)
d = torch.randn((), dtype=dtype, requires_grad=True)
e = torch.randn((), dtype=dtype, requires_grad=True)


learning_rate = 1e-7
for t in range(100000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + d * x ** 3 + e * x ** 5

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 10000 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        d -= learning_rate * d.grad
        d -= learning_rate * e.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        c.grad = None
        d.grad = None
        e.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {d.item()} x^3 + {e.item()} x^5')


99 383427.40625
10099 391310.25


KeyboardInterrupt: 

In [118]:
xx

tensor([[ -3.1416,   9.8696, -31.0063],
        [ -3.1384,   9.8499, -30.9133],
        [ -3.1353,   9.8301, -30.8205],
        ...,
        [  3.1353,   9.8301,  30.8205],
        [  3.1384,   9.8499,  30.9133],
        [  3.1416,   9.8696,  31.0063]], device='cuda:0')

In [117]:
import torch
import math


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Prepare the input tensor (x, x^2, x^3).
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use RMSprop; the optim package contains many other
# optimization algorithms. The first argument to the RMSprop constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-3
optimizer = torch.optim.RMSprop(model.parameters(), lr=learning_rate)
for t in range(2000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(xx)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()


linear_layer = model[0]
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')

99 2087.344970703125
199 1574.2977294921875
299 1345.9932861328125
399 1129.1258544921875
499 931.81884765625
599 756.5601196289062
699 602.7662353515625
799 469.18951416015625
899 354.90826416015625
999 259.009033203125
1099 180.67726135253906
1199 119.09180450439453
1299 73.21722412109375
1399 41.67363739013672
1499 22.522953033447266
1599 12.864471435546875
1699 9.52615737915039
1799 8.93216323852539
1899 8.926095962524414
1999 8.925756454467773
Result: y = 0.0005015641218051314 + 0.8570855855941772 x + 0.0005015628412365913 x^2 + -0.09279617667198181 x^3


In [120]:
# -*- coding: utf-8 -*-
import torch
import math


class Polynomial3(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate four parameters and assign them as
        member parameters.
        """
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(()))
        self.b = torch.nn.Parameter(torch.randn(()))
        self.c = torch.nn.Parameter(torch.randn(()))
        self.d = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        return self.a + self.b * x + self.c * x ** 2 + self.d * x ** 3

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = {self.a.item()} + {self.b.item()} x + {self.c.item()} x^2 + {self.d.item()} x^3'


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Construct our model by instantiating the class defined above
model = Polynomial3()

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters (defined 
# with torch.nn.Parameter) which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)
for t in range(20000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'Result: {model.string()}')

99 5085.8916015625
199 3439.41845703125
299 2329.237548828125
399 1579.9462890625
499 1073.7333984375
599 731.3973388671875
699 499.6471252441406
799 342.5948486328125
899 236.04977416992188
999 163.68997192382812
1099 114.492919921875
1199 81.00645446777344
1299 58.18792724609375
1399 42.620994567871094
1499 31.98900604248047
1599 24.71915626525879
1699 19.742523193359375
1799 16.331775665283203
1899 13.991594314575195
1999 12.384117126464844
2099 11.278669357299805
2199 10.51762580871582
2299 9.993104934692383
2399 9.631206512451172
2499 9.38125228881836
2599 9.208422660827637
2699 9.088798522949219
2799 9.0059232711792
2899 8.948451042175293
2999 8.90855598449707
3099 8.880836486816406
3199 8.861560821533203
3299 8.84814453125
3399 8.838798522949219
3499 8.832283973693848
3599 8.827737808227539
3699 8.824563980102539
3799 8.822344779968262
3899 8.820795059204102
3999 8.819709777832031
4099 8.818950653076172
4199 8.818418502807617
4299 8.818045616149902
4399 8.817784309387207
4499 8.

In [121]:
# -*- coding: utf-8 -*-
import random
import torch
import math


class DynamicNet(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate five parameters and assign them as members.
        """
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(()))
        self.b = torch.nn.Parameter(torch.randn(()))
        self.c = torch.nn.Parameter(torch.randn(()))
        self.d = torch.nn.Parameter(torch.randn(()))
        self.e = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 4, 5
        and reuse the e parameter to compute the contribution of these orders.

        Since each forward pass builds a dynamic computation graph, we can use normal
        Python control-flow operators like loops or conditional statements when
        defining the forward pass of the model.

        Here we also see that it is perfectly safe to reuse the same parameter many
        times when defining a computational graph.
        """
        y = self.a + self.b * x + self.c * x ** 2 + self.d * x ** 3
        for exp in range(4, random.randint(4, 6)):
            y = y + self.e * x ** exp
        return y

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = {self.a.item()} + {self.b.item()} x + {self.c.item()} x^2 + {self.d.item()} x^3 + {self.e.item()} x^4 ? + {self.e.item()} x^5 ?'


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Construct our model by instantiating the class defined above
model = DynamicNet()

# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-8, momentum=0.9)
for t in range(30000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 2000 == 1999:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'Result: {model.string()}')

1999 3376.126953125
3999 1523.5103759765625
5999 737.3735961914062
7999 319.46978759765625
9999 148.5950164794922
11999 75.62993621826172
13999 38.52421188354492
15999 22.107807159423828
17999 14.873477935791016
19999 11.55041217803955
21999 10.043790817260742
23999 9.381021499633789
25999 8.931184768676758
27999 8.932641983032227
29999 8.922027587890625
Result: y = -0.004001822788268328 + 0.8514901399612427 x + 0.0001422598579665646 x^2 + -0.0929984301328659 x^3 + 0.00010318189015379176 x^4 ? + 0.00010318189015379176 x^5 ?
