First, the most import element Tensor
Tensor is quite the same with ndarray in numpy 



In [36]:
import torch
import numpy as np
import math

In [2]:
t = torch.Tensor(5, 3)
n = np.empty((5, 3))
print(t, t.shape)
print(n, n.shape)

tensor([[ 1.5785e+18,  4.5841e-41,  1.5785e+18],
        [ 4.5841e-41,  1.0413e+09, -9.7947e-20],
        [-8.1188e-32,  4.5839e-41, -4.7726e-32],
        [ 4.5839e-41, -2.4910e-23,  1.1031e-37],
        [-8.1223e-32,  4.5839e-41, -4.7724e-32]]) torch.Size([5, 3])
[[2.8661412e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]] (5, 3)


In [3]:
torch.rand(5, 3)

tensor([[0.2028, 0.6863, 0.2941],
        [0.3226, 0.6021, 0.9086],
        [0.8982, 0.1444, 0.7632],
        [0.1940, 0.0420, 0.8208],
        [0.0470, 0.9708, 0.6122]])

In [4]:
t2 = torch.rand(5, 3)

In [5]:
t + t2

tensor([[1.5785e+18, 9.9412e-01, 1.5785e+18],
        [7.7773e-01, 1.0413e+09, 2.3234e-02],
        [7.2017e-01, 3.6664e-01, 4.6233e-01],
        [9.8669e-01, 1.0943e-01, 6.5858e-02],
        [6.8959e-01, 4.8997e-01, 2.0376e-01]])

In [6]:
torch.cuda.is_available()

True

In [7]:
from torch.autograd import Variable

x = Variable(torch.ones(2,2), requires_grad=True)

In [8]:
y = x + 2

In [9]:
z = y * y * 3

In [10]:
out = z.mean()

In [11]:
out.backward()

In [12]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [20]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.norm() < 1000:
    y = y * 2


In [21]:
gradients = torch.Tensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [79]:
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)
print(x, y)

[-3.14159265 -3.13844949 -3.13530633 ...  3.13530633  3.13844949
  3.14159265] [-1.22464680e-16 -3.14315906e-03 -6.28628707e-03 ...  6.28628707e-03
  3.14315906e-03  1.22464680e-16]


In [97]:
a = np.random.randn()
b = np.random.randn()
d = np.random.randn()
e = np.random.randn()

In [98]:
min_loss = np.inf


for t in range(10000):
    y_pred = a + b*x + d*x**3 

    loss = np.square(y - y_pred).sum() 
    if abs(min_loss - loss) < learning_rate:
        break
        
    if loss < min_loss:
        min_loss = np.inf
    
    if t % 500 == 99:
        print(t, loss)

    grad_y_pred = 2 * (y - y_pred)
    a_grad = grad_y_pred.sum()
    b_grad = (grad_y_pred * x).sum()
    d_grad = (grad_y_pred * x ** 3).sum()
    

    a += a_grad * learning_rate
    b += b_grad * learning_rate
    d += d_grad * learning_rate
   


print(f'Result: y = {a} + {b} x + {d} x^3 + {e} x^5 ')





99 2906.0783443431374
599 192.91712250469027
1099 28.78169988382963
1599 11.2810226767477
2099 9.127563862307282
2599 8.856387435105598
3099 8.82212366288763
3599 8.817792246667247
4099 8.817244657218932
4599 8.817175428771202
5099 8.817166676621355
5599 8.817165570137742
6099 8.817165430251425
6599 8.817165412566407
7099 8.817165410330592
7599 8.81716541004793
8099 8.817165410012198
8599 8.817165410007679
9099 8.817165410007107
9599 8.817165410007036
Result: y = -4.150906960851466e-17 + 0.8567408416997583 x + -0.09333038884515558 x^3 + -0.9335781556814468 x^5 


In [99]:
import torch
import math

dtype = torch.float64
device = torch.device('cpu')

device = torch.device("cuda:0") # Uncomment this to run on GPU




In [100]:
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

In [101]:
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)


In [105]:
for t in range(4000):
    y_pred = a + b*x + d*x**3 

    loss = (y - y_pred).pow(2).sum().item()
    if t % 5000 == 99:
        print(t, loss)

    grad_y_pred = 2 * (y - y_pred)
    a_grad = grad_y_pred.sum()
    b_grad = (grad_y_pred * x).sum()
    d_grad = (grad_y_pred * x ** 3).sum()

    a += a_grad * learning_rate
    b += b_grad * learning_rate
    d += d_grad * learning_rate
   


print(f'Result: y = {a.item()} + {b.item()} x + {d.item()} x^3')

99 15.683304604030335
Result: y = 5.570931458566834e-10 + 0.856715582089617 x + -0.0933267958855756 x^3


In [117]:
# -*- coding: utf-8 -*-
import torch
import math

dtype = torch.float
if torch.cuda.is_available():
    device = torch.device("cuda:0")  # You can specify the GPU index
    torch.cuda.set_device(device)
    print("Using GPU:", torch.cuda.get_device_name(device))
else:
    device = torch.device("cpu")
    print("CUDA is not available. Using CPU.")

# torch.set_default_device(device)

# Create Tensors to hold input and outputs.
# By default, requires_grad=False, which indicates that we do not need to
# compute gradients with respect to these Tensors during the backward pass.
x = torch.linspace(-math.pi, math.pi, 2000, dtype=dtype)
y = torch.sin(x)

# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), dtype=dtype, requires_grad=True)
b = torch.randn((), dtype=dtype, requires_grad=True)
c = torch.randn((), dtype=dtype, requires_grad=True)
d = torch.randn((), dtype=dtype, requires_grad=True)
e = torch.randn((), dtype=dtype, requires_grad=True)


learning_rate = 1e-7
for t in range(100000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + d * x ** 3 + e * x ** 5

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 10000 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        d -= learning_rate * d.grad
        d -= learning_rate * e.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        c.grad = None
        d.grad = None
        e.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {d.item()} x^3 + {e.item()} x^5')


Using GPU: NVIDIA GeForce GTX 1080
99 286951.21875
10099 283314.84375
20099 283313.21875
30099 283313.15625
40099 283313.1875
50099 283313.1875
60099 283313.1875
70099 283313.1875
80099 283313.1875
90099 283313.15625
Result: y = 2.406015084943647e-07 + 27.11090660095215 x + -11.561665534973145 x^3 + 0.9975190758705139 x^5


In [119]:
x.device

device(type='cpu')

In [116]:
[i for i in dir(torch) if 'device' in  i]

['_register_device_module', 'device', 'get_device']

In [118]:
xx

tensor([[ -3.1416,   9.8696, -31.0063],
        [ -3.1384,   9.8499, -30.9133],
        [ -3.1353,   9.8301, -30.8205],
        ...,
        [  3.1353,   9.8301,  30.8205],
        [  3.1384,   9.8499,  30.9133],
        [  3.1416,   9.8696,  31.0063]], device='cuda:0')

In [117]:
import torch
import math


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Prepare the input tensor (x, x^2, x^3).
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use RMSprop; the optim package contains many other
# optimization algorithms. The first argument to the RMSprop constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-3
optimizer = torch.optim.RMSprop(model.parameters(), lr=learning_rate)
for t in range(2000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(xx)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()


linear_layer = model[0]
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')

99 2087.344970703125
199 1574.2977294921875
299 1345.9932861328125
399 1129.1258544921875
499 931.81884765625
599 756.5601196289062
699 602.7662353515625
799 469.18951416015625
899 354.90826416015625
999 259.009033203125
1099 180.67726135253906
1199 119.09180450439453
1299 73.21722412109375
1399 41.67363739013672
1499 22.522953033447266
1599 12.864471435546875
1699 9.52615737915039
1799 8.93216323852539
1899 8.926095962524414
1999 8.925756454467773
Result: y = 0.0005015641218051314 + 0.8570855855941772 x + 0.0005015628412365913 x^2 + -0.09279617667198181 x^3


In [120]:
# -*- coding: utf-8 -*-
import torch
import math


class Polynomial3(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate four parameters and assign them as
        member parameters.
        """
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(()))
        self.b = torch.nn.Parameter(torch.randn(()))
        self.c = torch.nn.Parameter(torch.randn(()))
        self.d = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        return self.a + self.b * x + self.c * x ** 2 + self.d * x ** 3

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = {self.a.item()} + {self.b.item()} x + {self.c.item()} x^2 + {self.d.item()} x^3'


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Construct our model by instantiating the class defined above
model = Polynomial3()

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters (defined 
# with torch.nn.Parameter) which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)
for t in range(20000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'Result: {model.string()}')

99 5085.8916015625
199 3439.41845703125
299 2329.237548828125
399 1579.9462890625
499 1073.7333984375
599 731.3973388671875
699 499.6471252441406
799 342.5948486328125
899 236.04977416992188
999 163.68997192382812
1099 114.492919921875
1199 81.00645446777344
1299 58.18792724609375
1399 42.620994567871094
1499 31.98900604248047
1599 24.71915626525879
1699 19.742523193359375
1799 16.331775665283203
1899 13.991594314575195
1999 12.384117126464844
2099 11.278669357299805
2199 10.51762580871582
2299 9.993104934692383
2399 9.631206512451172
2499 9.38125228881836
2599 9.208422660827637
2699 9.088798522949219
2799 9.0059232711792
2899 8.948451042175293
2999 8.90855598449707
3099 8.880836486816406
3199 8.861560821533203
3299 8.84814453125
3399 8.838798522949219
3499 8.832283973693848
3599 8.827737808227539
3699 8.824563980102539
3799 8.822344779968262
3899 8.820795059204102
3999 8.819709777832031
4099 8.818950653076172
4199 8.818418502807617
4299 8.818045616149902
4399 8.817784309387207
4499 8.

In [121]:
# -*- coding: utf-8 -*-
import random
import torch
import math


class DynamicNet(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate five parameters and assign them as members.
        """
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(()))
        self.b = torch.nn.Parameter(torch.randn(()))
        self.c = torch.nn.Parameter(torch.randn(()))
        self.d = torch.nn.Parameter(torch.randn(()))
        self.e = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 4, 5
        and reuse the e parameter to compute the contribution of these orders.

        Since each forward pass builds a dynamic computation graph, we can use normal
        Python control-flow operators like loops or conditional statements when
        defining the forward pass of the model.

        Here we also see that it is perfectly safe to reuse the same parameter many
        times when defining a computational graph.
        """
        y = self.a + self.b * x + self.c * x ** 2 + self.d * x ** 3
        for exp in range(4, random.randint(4, 6)):
            y = y + self.e * x ** exp
        return y

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = {self.a.item()} + {self.b.item()} x + {self.c.item()} x^2 + {self.d.item()} x^3 + {self.e.item()} x^4 ? + {self.e.item()} x^5 ?'


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Construct our model by instantiating the class defined above
model = DynamicNet()

# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-8, momentum=0.9)
for t in range(30000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 2000 == 1999:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'Result: {model.string()}')

1999 3376.126953125
3999 1523.5103759765625
5999 737.3735961914062
7999 319.46978759765625
9999 148.5950164794922
11999 75.62993621826172
13999 38.52421188354492
15999 22.107807159423828
17999 14.873477935791016
19999 11.55041217803955
21999 10.043790817260742
23999 9.381021499633789
25999 8.931184768676758
27999 8.932641983032227
29999 8.922027587890625
Result: y = -0.004001822788268328 + 0.8514901399612427 x + 0.0001422598579665646 x^2 + -0.0929984301328659 x^3 + 0.00010318189015379176 x^4 ? + 0.00010318189015379176 x^5 ?
