In [8]:
import torch
import numpy as np

In [5]:
torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [17]:
device = torch.device(0)

In [22]:
a_np_array = np.array([[1,2], [3,4]])
tensor = torch.from_numpy(a_np_array)
t = tensor.to(device, dtype=torch.float32)
t

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [25]:
shape = (2, 3)
print(torch.rand(shape))
print(torch.ones(shape))
print(torch.ones_like(t, device=device, dtype=torch.float64))
print(torch.zeros(shape))
print(torch.zeros_like(t))

tensor([[0.9087, 0.5382, 0.0438],
        [0.7261, 0.6863, 0.8056]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')


In [27]:
print(t.shape, t.dtype, t.device)

torch.Size([2, 2]) torch.float32 cuda:0


In [31]:
a_tensor = torch.randint(10, (4, 5))
a_tensor

tensor([[7, 0, 4, 9, 0],
        [1, 0, 6, 2, 5],
        [4, 3, 7, 8, 0],
        [1, 0, 3, 3, 6]])

In [33]:
a_tensor[0]

tensor([7, 0, 4, 9, 0])

In [34]:
a_tensor[..., -1]

tensor([0, 5, 0, 6])

In [36]:
a_tensor[::2, ::2]

tensor([[7, 4, 0],
        [4, 7, 0]])

In [38]:
a_tensor[::2, ::2] = 2
a_tensor 

tensor([[2, 0, 2, 9, 2],
        [1, 0, 6, 2, 5],
        [2, 3, 2, 8, 2],
        [1, 0, 3, 3, 6]])

In [42]:
torch.cat((a_tensor, a_tensor), dim=1)

tensor([[2, 0, 2, 9, 2, 2, 0, 2, 9, 2],
        [1, 0, 6, 2, 5, 1, 0, 6, 2, 5],
        [2, 3, 2, 8, 2, 2, 3, 2, 8, 2],
        [1, 0, 3, 3, 6, 1, 0, 3, 3, 6]])

In [59]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.concatenate((a, b), axis=None))
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))

print("-" * 30)

a = np.array([[[1, 2], [3, 4]]])
b = np.array([[[5, 6], [7, 8]]])
print(a.shape, b.shape)
print(np.concatenate((a, b), axis=None), np.concatenate((a, b), axis=None).shape)
print(np.concatenate((a, b), axis=0), np.concatenate((a, b), axis=0),shape)
print(np.concatenate((a, b), axis=1), np.concatenate((a, b), axis=1).shape)
print(np.concatenate((a, b), axis=2), np.concatenate((a, b), axis=2).shape)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 7]
 [3 4 6 8]]
------------------------------
(1, 2, 2) (1, 2, 2)
[1 2 3 4 5 6 7 8] (8,)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 3)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]] (1, 4, 2)
[[[1 2 5 6]
  [3 4 7 8]]] (1, 2, 4)


In [61]:
import torch

In [65]:
a = torch.randn(2,2 ,requires_grad=True)
b = torch.randn(2,2, requires_grad=True)

In [66]:
Q = 3 * a**3 - 2 * b ** 2

In [67]:
a, b

(tensor([[ 0.7778, -0.5615],
         [-0.2789,  0.2117]], requires_grad=True),
 tensor([[ 1.0669, -1.9701],
         [ 0.5104, -0.0819]], requires_grad=True))

In [69]:
external_grad = torch.tensor([[1., 1.], [1., 1.]])
Q.backward(gradient=external_grad)

In [73]:
print(9*a**2 == a.grad)
print(-4*b == b.grad)


tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])


In [71]:
a.grad

tensor([[5.4441, 2.8376],
        [0.7000, 0.4034]])